# Generated by Django 5.0.3 on 2024-04-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('battery_life', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='plant_type',
            new_name='water_source',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='irrigated',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='irrigation_frequency',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='moisture_level',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='water_consumption',
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('irrigated', models.BooleanField(default=False)),
                ('moisture_level', models.FloatField(blank=True, null=True)),
                ('plant_type', models.CharField(max_length=255)),
                ('water_consumption', models.FloatField(blank=True, null=True)),
                ('irrigation_frequency', models.IntegerField(blank=True, null=True)),
                ('expected_yield', models.FloatField(blank=True, null=True)),
                ('water_requirements', models.FloatField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='sensors',
            field=models.ManyToManyField(to='main.sensor'),
        ),
    ]
